version: '2'
services:

  nlp:
    image: python:2.7.12
    container_name: "phaseduo_nlp"
    build: .
    command: "python phaseduo_nlp/app.py"
    ports:
      - "8000:8000"
    volumes:
      - ".:/phaseduo_nlp"
    env_file: .env
